### ISSUE TITLE
Can't login because Google login method is updated

### ISSUE THREAD

**Issue by cnrting** [3846masa/upload-gphotos#321] opened 2018-10-16 07:48 UTC
It's not a new account and I have login many times before using that ip address(Diditalocean),I have try https://accounts.google.com/b/0/DisplayUnlockCaptcha but still not working which should work before.

ERROR Failed to login. Failed to login
{ version: 'tough-cookie@2.4.3',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies: 
   [ { key: 'NID',
       value: '141=mqHqnLmvSDxQNLm************************SRqZnuPAT_VPNDGU',
       expires: '2019-04-17T06:52:40.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2018-10-16T06:52:40.556Z',
       lastAccessed: '2018-10-16T06:52:40.893Z' },
     { key: 'GAPS',
       value: '1:pc1OViI3POA9L_piDXahCPMAxAf4*******************',
       expires: '2020-10-15T06:52:40.000Z',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       httpOnly: true,
       extensions: [Object],
       hostOnly: true,
       creation: '2018-10-16T06:52:40.772Z',
       lastAccessed: '2018-10-16T06:52:40.893Z' } ] }
ERROR Error: Failed to login
    at GPhotos.<anonymous> (/usr/lib/node_modules/upload-gphotos/lib/index.js:126:39)
    at next (native)
    at fulfilled (/usr/lib/node_modules/upload-gphotos/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 1: node::Abort() [node]
 2: 0x710f69 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0x82aaeb [node]
 5: 0x82b2de [node]
 6: 0x838c7e [node]
 7: 0x17d0406092a7
Aborted

**Comment by ManuCart** [comment] 2018-10-16 08:51
Hi same for me, to bad, need to use flickr

**Comment by 3846masa** [comment] 2018-10-16 09:01
Google's login form is updated. I'll fix it, but it takes a few days.

**Comment by 3846masa** [comment] 2018-10-16 09:13
I changed login method to `nojavascript` mode at v2.0.13.
Please try it.

If you can upload using v2.0.13, close this issue.

**Comment by ManuCart** [comment] 2018-10-16 12:03
No way with this error
````
ERROR Failed to login. Failed to login
{ version: 'tough-cookie@2.4.3',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies:
   [ { key: 'NID',
       value:
        '141=FBaIxEXS4D_oARSBMJqw2laxTiXsAwdFkLYsIcJAqFu5uCrFRvB3HjT7iqA-TTzABTVBkXwggVQ7YJguqB5D04u_xCQDLQZfkXgfWzmC3D_B_pNIPf6MlgPzpRBq1axc',
       expires: '2019-04-17T11:59:43.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2018-10-16T11:59:44.111Z',
       lastAccessed: '2018-10-16T11:59:51.000Z' },
     { key: 'GAPS',
       value: '1:BKCJGKzsg0Y12yLff6O0JvoNTeum3Q:R9zATf30tk6X6C6x',
       expires: '2020-10-15T11:59:51.000Z',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       httpOnly: true,
       extensions: [Array],
       hostOnly: true,
       creation: '2018-10-16T11:59:45.048Z',
       lastAccessed: '2018-10-16T11:59:51.379Z' },
     { key: 'GALX',
       value: 'h5iwX_EQO_I',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       hostOnly: true,
       creation: '2018-10-16T11:59:48.032Z',
       lastAccessed: '2018-10-16T11:59:51.000Z' } ] }
ERROR Error: Failed to login
    at GPhotos.<anonymous> (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:127:39)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/upload-gphotos/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Aborted
````

**Comment by cnrting** [comment] 2018-10-16 16:29
2.0.13 encounted same error：
ERROR Failed to login. Failed to login
{ version: 'tough-cookie@2.4.3',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies: 
   [ { key: 'NID',
       value: '141=HxSJRE**********W4BLiBaV_oVtnIHYT3SMvXyk6GrCRWN_Z',
       expires: '2019-04-17T16:27:12.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2018-10-16T16:27:12.402Z',
       lastAccessed: '2018-10-16T16:27:13.379Z' },
     { key: 'GAPS',
       value: '1:cUV*****HPCY',
       expires: '2020-10-15T16:27:13.000Z',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       httpOnly: true,
       extensions: [Object],
       hostOnly: true,
       creation: '2018-10-16T16:27:12.646Z',
       lastAccessed: '2018-10-16T16:27:13.379Z' },
     { key: 'GALX',
       value: '8Nh7K56OjOM',
       domain: 'accounts.google.com',
       path: '/',
       secure: true,
       hostOnly: true,
       creation: '2018-10-16T16:27:12.923Z',
       lastAccessed: '2018-10-16T16:27:13.379Z' } ] }
ERROR Error: Failed to login
    at GPhotos.<anonymous> (/usr/lib/node_modules/upload-gphotos/lib/index.js:123:39)
    at next (native)
    at fulfilled (/usr/lib/node_modules/upload-gphotos/lib/index.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 1: node::Abort() [node]
 2: 0x710f69 [node]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
 4: 0x82aaeb [node]
 5: 0x82b2de [node]
 6: 0x838c7e [node]
 7: 0x3dadee4092a7

**Comment by 3846masa** [comment] 2018-10-17 04:29
Umm...
It works in my environment...

I'll research why login is failed.

**Comment by 3846masa** [comment] 2018-10-17 04:33
note:

If you can write JavaScript, you may read cookie from firefox using https://github.com/JSBizon/db-cookie-store (but I don't check it yet).

**Comment by ManuCart** [comment] 2018-10-25 16:46
Hi,
What's the news?
On my side no way to make it work your script.

**Comment by 3846masa** [comment] 2018-10-25 23:00
I think Google use different login page per user-agent.
Try it, and please report feedback.

```js
const GPhotos = require('upload-gphotos').default;

(async () => {
  const gphotos = new GPhotos({ username: '****', password: '****' });
  // Change user-agent as Chrome
  gphotos.axios.defaults.headers = {
    'User-Agent':
      'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
  };
  await gphotos.login();

  const photo = await gphotos.upload(filePath);
  console.log(photo);
})();
```

**Comment by 3846masa** [comment] 2018-10-27 01:10
Thanks for reporting.

I have no idea to solve this issue because it works in my environment. Sorry.
When this issue cause in my environment, I'll retry to research.

**Comment by cnrting** [comment] 2018-10-30 17:03
@3846masa on my side,some accounts fail to login,but others accounts works

**Comment by 3846masa** [comment] 2018-11-02 01:55
Note: https://security.googleblog.com/2018/10/announcing-some-security-treats-to.html?m=1

I will update signin method using client JavaScript, maybe fix this issue.

**Comment by mcortinas** [comment] 2018-11-25 10:52
any update? I have the same problem....

**Comment by it-guru** [comment] 2018-12-18 13:56
I have the same problem. I would be grateful for updates ...

**Comment by meotimdihia** [comment] 2019-02-20 15:15
I think we can close this issue. It works for me.

**Comment by Guilty-King** [comment] 2019-03-15 17:04
@3846masa , thank you for actively developing the project but I am facing a similar login issue while using v3.0.4 linux binary 
last binary i used and was working for me was a few months ago and probably v2.x.x

For current release v3.0.4 i get the following error 

```
upload-gphotos "test.mkv" -u "gmail27@gmail.com" -p "qwerty123"
ERROR Failed to login. waiting for selector "input[type="email"]" failed: timeout 30000ms exceeded
{ version: 'tough-cookie@3.0.0',
  storeType: 'MemoryCookieStore',
  rejectPublicSuffixes: true,
  cookies:
   [ { key: 'NID',
       value: '164=Dop2YNPz0fNdSpdI8PAiCMPnPMDWtp8fpjOX-pf4f-xIweX4ih7pEDvE0MgFgHAgBt2CeHA9bCwuJszdHRE8B-SoZF9yGa6mI08Y4sVnJPGJ8APfPeNt4DWD1PiqfXIZuinIsjo8VOaF4fyVuHFo2D-du4gWy7r40taPLeBZOTo',
       expires: '2019-09-14T16:48:28.000Z',
       domain: 'google.com',
       path: '/',
       httpOnly: true,
       hostOnly: false,
       creation: '2019-03-15T16:48:28.608Z',
       lastAccessed: '2019-03-15T16:48:28.608Z' } ] }
ERROR TimeoutError: waiting for selector "input[type="email"]" failed: timeout 30000ms exceeded
    at new WaitTask (/snapshot/project/node_modules/puppeteer-core/lib/FrameManager.js:991:28)
    at Frame._waitForSelectorOrXPath (/snapshot/project/node_modules/puppeteer-core/lib/FrameManager.js:882:12)
    at Frame.waitForSelector (/snapshot/project/node_modules/puppeteer-core/lib/FrameManager.js:836:17)
    at Page.waitForSelector (/snapshot/project/node_modules/puppeteer-core/lib/Page.js:1031:29)
    at GPhotos.<anonymous> (/snapshot/project/lib/index.js:129:26)
    at Generator.next (<anonymous>)
    at fulfilled (/snapshot/project/lib/index.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 1: node::Abort() [upload-gphotos]
 2: 0x8bd979 [upload-gphotos]
 3: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [upload-gphotos]
 4: 0xabfd0c [upload-gphotos]
 5: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [upload-gphotos]
 6: 0x1a09690842fd
Aborted (core dumped)
```

I have checked that the account is accessible from server using this script 
```
const GPhotos = require('upload-gphotos').default;
const gphotos = new GPhotos({
          username: 'gmail27@gmail.com',
          password: 'qwerty123',
});

gphotos.postLogin()
  .then(() => gphotos.axios.get('https://photos.google.com'))
  .then((res) => console.log(res.status, res.headers['location']));
```

where output is 
`200 undefined`

and i think the cause of latest binary not working for me is user-agent 
i ran the following code you mentioned above 
```
const GPhotos = require('upload-gphotos').default;

(async () => {
          const gphotos = new GPhotos({ username: 'gmail27@gmail.com', password: 'qwerty123' });
          // Change user-agent as Chrome
gphotos.axios.defaults.headers = {
            'User-Agent':
              'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36',
          };
          await gphotos.login();

          const photo = await gphotos.upload('test.jpg');
          console.log(photo);
})();
```

output
```
GPhotosPhoto {
  type: 'photo',
  id: 'AF1QipNgWzxVtET3kTn_qRFZHhga4bcnM4kYjDdz_5U8',
  uploadedAt: 2019-03-15T16:58:14.930Z,
  createdAt: 2019-03-14T13:22:33.251Z,
  title: 'test.jpg',
  description: '',
  rawUrl: 'https://lh3.googleusercontent.com/-W1iwimEgCKU/XIpVmZu1WAI/AAAAAAAAO40/Dtq-ecvX5D8XMM_dDE0ZGqwYzJRnuiYrQCLcBCAs/test.jpg' }
```
and could you help me on how to use Chrome (Puppeteer) with the linux binary as Puppeteer is a npm module 

Hope you could develop this project further

**Comment by 3846masa** [comment] 2019-06-09 01:23
`upload-gphotos@3.1.0` supports to load cookies from JSON file.
Please use this option if failed to login with username and password.

**Closed by 3846masa** 2019-06-09 01:23 UTC
Labels: bug
